//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EPUConsole.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.1.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DefaultEndpointsProtocol=https;AccountName=epustorage;AccountKey=jiHZtHwoogsqv25f" +
            "SfaHDYsdd4vcG+nC5bjimO3CkNMfK0PIe31FNK28qx3iKkkD0mvkCDhTXjyC8n+0vQxGfQ==;Endpoin" +
            "tSuffix=core.windows.net")]
        public string blobConnStr {
            get {
                return ((string)(this["blobConnStr"]));
            }
            set {
                this["blobConnStr"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Is there a motorcycle in this picture?")]
        public string displayQuestion {
            get {
                return ((string)(this["displayQuestion"]));
            }
            set {
                this["displayQuestion"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("epluribusunum")]
        public string database {
            get {
                return ((string)(this["database"]));
            }
            set {
                this["database"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("workitems")]
        public string collection {
            get {
                return ((string)(this["collection"]));
            }
            set {
                this["collection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5prZGHqPMoAAtTAKFmUo0vDOkhhsU1W9elwzA9KaB0U4n29DKLbBb8qkafqNkDN3TkhekRqSPdfR2Z1sd" +
            "8ZOEg==")]
        public string authKey {
            get {
                return ((string)(this["authKey"]));
            }
            set {
                this["authKey"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://epluribusunum.documents.azure.com:443/")]
        public string endPoint {
            get {
                return ((string)(this["endPoint"]));
            }
            set {
                this["endPoint"] = value;
            }
        }
    }
}
